apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
  namespace: munbon-databases
type: Opaque
stringData:
  admin-username: admin
  admin-password: ChangeMeInProduction123!
  admin-token: ChangeMeToSecureTokenInProduction
  init-username: admin
  init-password: ChangeMeInProduction123!
  init-org: munbon
  init-bucket: metrics