version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: munbon-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - munbon-network

volumes:
  redis-data:

networks:
  munbon-network:
    external: true