# Minimal Docker Compose - Just Essential Databases
# For development when disk space is limited

services:
  # PostgreSQL with PostGIS
  postgres:
    image: postgis/postgis:15-3.3  # Standard version
    container_name: munbon-postgres
    environment:
      POSTGRES_DB: munbon_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G

  # TimescaleDB
  timescaledb:
    image: timescale/timescaledb:latest-pg15  # Standard version
    container_name: munbon-timescaledb
    environment:
      POSTGRES_DB: munbon_timescale
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - timescale-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  postgres-data:
  timescale-data:

networks:
  default:
    name: munbon-network
    driver: bridge