version: '3.8'

services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: munbon-cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate --url https://c0zc2kfzd6.execute-api.ap-southeast-1.amazonaws.com
    environment:
      - TUNNEL_METRICS=0.0.0.0:2000
    labels:
      - "com.munbon.description=Cloudflare Tunnel for TLS 1.0+ support"
      - "com.munbon.supports=SSL 3.0, TLS 1.0, TLS 1.1, TLS 1.2, TLS 1.3"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Tunnel with permanent configuration
  cloudflare-tunnel-permanent:
    image: cloudflare/cloudflared:latest
    container_name: munbon-cloudflare-tunnel-permanent
    restart: unless-stopped
    command: tunnel run
    volumes:
      - ~/.cloudflared:/home/nonroot/.cloudflared
    profiles:
      - permanent
    depends_on:
      - tunnel-config-generator

  # Helper service to show tunnel URL
  tunnel-config-generator:
    image: alpine:latest
    container_name: tunnel-url-extractor
    volumes:
      - ./tunnel-info:/info
    command: |
      sh -c "
        apk add --no-cache curl jq
        echo 'Waiting for tunnel to start...'
        sleep 10
        # Extract logs from cloudflare-tunnel container
        docker logs munbon-cloudflare-tunnel 2>&1 | grep -o 'https://[a-zA-Z0-9\-]*\.trycloudflare\.com' | head -1 > /info/tunnel-url.txt
        if [ -s /info/tunnel-url.txt ]; then
          echo 'Tunnel URL saved to ./tunnel-info/tunnel-url.txt'
          cat /info/tunnel-url.txt
        else
          echo 'Failed to extract tunnel URL'
        fi
      "
    profiles:
      - setup

# Networks
networks:
  default:
    name: munbon-tunnel-network

# Volumes for persistent data
volumes:
  tunnel-config:
    driver: local