apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescaledb
spec:
  template:
    spec:
      containers:
      - name: timescaledb
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"