apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: munbon-databases
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: postgis/postgis:15-3.3
            command:
            - /bin/bash
            - -c
            - |
              set -e
              DATE=$(date +%Y%m%d_%H%M%S)
              BACKUP_FILE="/backup/munbon_${DATE}.sql.gz"
              
              echo "Starting backup at $(date)"
              
              # Create backup
              PGPASSWORD=$POSTGRES_PASSWORD pg_dump \
                -h postgres-primary \
                -U postgres \
                -d munbon_prod \
                --verbose \
                --no-owner \
                --no-acl \
                --format=custom \
                --compress=9 \
                > "${BACKUP_FILE}"
              
              echo "Backup completed: ${BACKUP_FILE}"
              
              # Clean old backups (keep last 30 days)
              find /backup -name "munbon_*.sql.gz" -mtime +30 -delete
              
              echo "Backup process completed at $(date)"
            env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            volumeMounts:
            - name: backup
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: postgres-backup-pvc