apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-secret
  labels:
    app: timescaledb
    component: database
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: timescale-munbon-2024!
  POSTGRES_DB: postgres
  # Replication user for future HA setup
  REPLICATION_USER: replicator
  REPLICATION_PASSWORD: repl-munbon-2024!
  # Application user
  APP_USER: sensor_service
  APP_PASSWORD: sensor-munbon-2024!
  # Backup user
  BACKUP_USER: backup_user
  BACKUP_PASSWORD: backup-munbon-2024!