apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-pvc
  namespace: munbon-databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: standard  # Change based on your cluster
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: munbon-databases
spec:
  schedule: "0 3 * * *"  # Daily at 3 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: mongo:7
            command:
            - /bin/bash
            - -c
            - |
              set -e
              DATE=$(date +%Y%m%d_%H%M%S)
              BACKUP_DIR="/backup/munbon_mongo_${DATE}"
              
              echo "Starting MongoDB backup at $(date)"
              
              # Create backup using mongodump
              mongodump \
                --host="mongodb-0.mongodb:27017,mongodb-1.mongodb:27017,mongodb-2.mongodb:27017" \
                --username=$MONGO_INITDB_ROOT_USERNAME \
                --password=$MONGO_INITDB_ROOT_PASSWORD \
                --authenticationDatabase=admin \
                --oplog \
                --gzip \
                --out="${BACKUP_DIR}"
              
              echo "Backup completed: ${BACKUP_DIR}"
              
              # Create a compressed archive
              cd /backup
              tar -czf "munbon_mongo_${DATE}.tar.gz" "munbon_mongo_${DATE}"
              rm -rf "munbon_mongo_${DATE}"
              
              # Clean old backups (keep last 30 days)
              find /backup -name "munbon_mongo_*.tar.gz" -mtime +30 -delete
              
              echo "Backup process completed at $(date)"
            env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            volumeMounts:
            - name: backup
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: mongodb-backup-pvc