apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}-config
data:
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  API_PREFIX: "/api/v1"
  API_RATE_LIMIT_WINDOW_MS: "900000"
  API_RATE_LIMIT_MAX_REQUESTS: "100"
  HEALTH_CHECK_TIMEOUT_MS: "5000"