apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: munbon
  labels:
    app: auth-service
    service: core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: munbon/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: munbon-config
              key: NODE_ENV
        - name: PORT
          value: "3000"
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: munbon-config
              key: POSTGRES_HOST
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: munbon-config
              key: REDIS_HOST
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: munbon
spec:
  selector:
    app: auth-service
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: munbon
type: Opaque
data:
  jwt-secret: bXVuYm9uX2p3dF9zZWNyZXRfa2V5XzIwMjU= # munbon_jwt_secret_key_2025 (base64)