apiVersion: v1
kind: ConfigMap
metadata:
  name: munbon-config
  namespace: munbon
data:
  NODE_ENV: "production"
  API_PORT: "3000"
  LOG_LEVEL: "info"
  REDIS_HOST: "redis-service.munbon.svc.cluster.local"
  POSTGRES_HOST: "postgres-service.munbon.svc.cluster.local"
  MONGO_HOST: "mongodb-service.munbon.svc.cluster.local"
  INFLUXDB_HOST: "influxdb-service.munbon.svc.cluster.local"
  KAFKA_BROKERS: "kafka-0.kafka-headless.munbon.svc.cluster.local:9092"