version: '3.8'

services:
  sensor-network-management:
    build: .
    ports:
      - "3023:3023"
    environment:
      - SERVICE_NAME=sensor-network-management
      - SERVICE_PORT=3023
      - ENVIRONMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=munbon_sensors
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=your_influxdb_token
      - INFLUXDB_ORG=munbon
      - INFLUXDB_BUCKET=sensor_data
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MOCK_SERVER_URL=http://mock-server:3099
    depends_on:
      - postgres
      - influxdb
      - redis
    networks:
      - munbon-network

  postgres:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_DB=munbon_sensors
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - munbon-network

  influxdb:
    image: influxdb:2.7
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=munbon
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your_influxdb_token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - munbon-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - munbon-network

volumes:
  postgres_data:
  influxdb_data:
  redis_data:

networks:
  munbon-network:
    driver: bridge