version: '3.8'

services:
  water-accounting:
    build: .
    container_name: water-accounting-service
    ports:
      - "3024:3024"
    environment:
      - SERVICE_NAME=water-accounting-service
      - SERVICE_PORT=3024
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=munbon_water_accounting
      - DATABASE_USER=water_accounting_user
      - DATABASE_PASSWORD=water_accounting_pass
      - TIMESCALE_HOST=timescaledb
      - TIMESCALE_PORT=5432
      - TIMESCALE_NAME=munbon_timeseries
      - TIMESCALE_USER=timescale_user
      - TIMESCALE_PASSWORD=timescale_pass
      - FLOW_MONITORING_URL=http://flow-monitoring:3016/api/v1
      - SCHEDULER_URL=http://scheduler:3017/api/v1
      - MOCK_SERVER_URL=http://mock-server:3099/api/v1
    depends_on:
      - postgres
      - timescaledb
    networks:
      - munbon-network
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  postgres:
    image: postgis/postgis:15-3.3
    container_name: water-accounting-postgres
    environment:
      - POSTGRES_DB=munbon_water_accounting
      - POSTGRES_USER=water_accounting_user
      - POSTGRES_PASSWORD=water_accounting_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - munbon-network

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: water-accounting-timescale
    environment:
      - POSTGRES_DB=munbon_timeseries
      - POSTGRES_USER=timescale_user
      - POSTGRES_PASSWORD=timescale_pass
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - munbon-network

  mock-server:
    build: ../flow-monitoring/mock-server
    container_name: mock-server
    ports:
      - "3099:3099"
    networks:
      - munbon-network

networks:
  munbon-network:
    driver: bridge

volumes:
  postgres_data:
  timescale_data: