name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

          # Create deployment script
          cat > deploy.sh << 'DEPLOY_SCRIPT'
          #!/bin/bash
          set -e
          
          echo "=== Starting deployment ==="
          cd /home/ubuntu/munbon2-backend
          
          # Pull latest images from Docker Hub
          echo "Pulling latest images..."
          docker pull subhaj888/munbon-sensor-data:latest
          docker pull subhaj888/munbon-auth:latest
          docker pull subhaj888/munbon-gis:latest
          
          # Update docker-compose with Docker Hub images
          export DOCKERHUB_USERNAME=subhaj888
          
          # Stop existing services
          echo "Stopping existing services..."
          docker-compose -f docker-compose.ec2.yml down || true
          
          # Start services with new images
          echo "Starting services..."
          docker-compose -f docker-compose.ec2.yml up -d sensor-data auth gis
          
          # Show status
          echo "=== Deployment complete ==="
          docker-compose -f docker-compose.ec2.yml ps
          DEPLOY_SCRIPT

          # Copy and execute deployment script
          scp -i ~/.ssh/deploy_key deploy.sh "$EC2_USER@$EC2_HOST:/tmp/"
          ssh -i ~/.ssh/deploy_key "$EC2_USER@$EC2_HOST" 'bash /tmp/deploy.sh'