name: Docker Simple Test

on:
  workflow_dispatch:

# Cancel any in-progress runs
concurrency:
  group: docker-build
  cancel-in-progress: true

jobs:
  quick-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Quick test
        run: |
          echo "Testing GitHub Actions..."
          echo "Runner: $(hostname)"
          echo "Time: $(date)"
          docker --version
          
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test Docker Hub login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "Username is set: $(if [ -n "$DOCKERHUB_USERNAME" ]; then echo "Yes"; else echo "No"; fi)"
          echo "Token is set: $(if [ -n "$DOCKERHUB_TOKEN" ]; then echo "Yes"; else echo "No"; fi)"
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          echo "✅ Docker Hub login successful!"