name: Docker Hub Simple Build

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test sensor-data
        run: |
          echo "=== Building sensor-data ==="
          cd services/sensor-data
          
          # Check what we have
          echo "Files in directory:"
          ls -la
          
          # Create simple Dockerfile
          cat > Dockerfile << 'EOF'
          FROM node:20-alpine
          WORKDIR /app
          COPY package*.json ./
          RUN npm install --production --force || true
          COPY . .
          EXPOSE 3001
          CMD ["node", "src/index.js"]
          EOF
          
          # Build and push
          docker build -t subhaj888/munbon-sensor-data:latest .
          docker push subhaj888/munbon-sensor-data:latest
          
          echo "✅ sensor-data complete"

      - name: Build and test auth
        run: |
          echo "=== Building auth ==="
          cd services/auth
          
          # Create simple Dockerfile
          cat > Dockerfile << 'EOF'
          FROM node:20-alpine
          WORKDIR /app
          COPY package*.json ./
          RUN npm install --production --force || true
          COPY . .
          EXPOSE 3000
          CMD ["node", "src/index.js"]
          EOF
          
          # Build and push
          docker build -t subhaj888/munbon-auth:latest .
          docker push subhaj888/munbon-auth:latest
          
          echo "✅ auth complete"

      - name: Build and test gis
        run: |
          echo "=== Building gis ==="
          cd services/gis
          
          # Create simple Dockerfile
          cat > Dockerfile << 'EOF'
          FROM node:20-alpine
          WORKDIR /app
          COPY package*.json ./
          RUN npm install --production --force || true
          COPY . .
          EXPOSE 3000
          CMD ["node", "src/index.js"]
          EOF
          
          # Build and push
          docker build -t subhaj888/munbon-gis:latest .
          docker push subhaj888/munbon-gis:latest
          
          echo "✅ gis complete"

      - name: Verify images exist
        run: |
          echo "=== Verifying images on Docker Hub ==="
          docker images | grep munbon || true
          echo "All images built and pushed successfully!"