name: Test Secrets Access

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test secret access
        run: |
          echo "Testing secrets..."
          echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "EC2_USER: ${{ secrets.EC2_USER }}"
          echo "EC2_SSH_KEY exists: ${{ secrets.EC2_SSH_KEY != '' && 'YES' || 'NO' }}"
          
      - name: Test SSH connection with hardcoded values
        run: |
          # Since we know EC2_HOST is 43.209.22.250 and EC2_USER is ubuntu
          mkdir -p ~/.ssh
          
          # Write the key with proper formatting
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          
          chmod 600 ~/.ssh/deploy_key
          
          # Show key info (safe - just metadata)
          echo "Key file size: $(wc -c < ~/.ssh/deploy_key) bytes"
          echo "Key first line: $(head -1 ~/.ssh/deploy_key | cut -c1-30)..."
          
          # Test connection
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ubuntu@43.209.22.250 "echo 'SUCCESS: Connected to EC2!'"